### ISSUE TITLE
uber-uns.php

### ISSUE THREAD

**Issue by junktexelstorm** [tuanvuf4/champi#12]
- White boxes should be red. Compare to original
- Forgot to change sub page: geschichte-der-thai-traditional-massage.php
- Text color is different. Original white. Here black
- Text in "Unser Team" box doesn't wrap when page width is smaller. See:
![image](https://user-images.githubusercontent.com/16895685/32544044-a3516e54-c477-11e7-91d1-652f4a4f4652.png)

**Comment by tuanvuf4** [comment]
Text in "Unser Team" box doesn't wrap when page width is smaller.

**Comment by junktexelstorm** [comment]
Done
